plugins:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
    - CONTRIBUTING.md
    - README.md
    - LICENSE.md
    - COPYING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - _posts
    - _layouts
    - _assets
    - _drafts
theme: jekyll-theme-tactile
